### ISSUE TITLE
Cloud you use the pre-compiled llvm?

### ISSUE THREAD

**Issue by chena1982** [Leandros/metareflect#1]
Compile the llvm is so boring.
Or you need debug the llvm?
Thanks.

**Comment by Leandros** [comment]
No, you cannot use pre-compiled LLVM, since the tool is build as part of clang.

**Comment by reductor** [comment]
One possibility is to move it over to libclang which is a "C" API then you don't need to build it as part of clang and can easily link it to the exposed API

**Comment by Leandros** [comment]
Yes, I've considered this when starting the project, but quickly came to the conclusion that libclang is considerably less powerful and would not allow this simple of an implementation as right now.
